language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .
  - pip install pillow
# command to run tests, e.g. python setup.py test
script:
  nosetests --with-coverage --cover-package=neo
